# Site settings
title: Kowin Shi
email: kowinshi@hotmail.com
url: http://skookumasfrig.github.io
description: "Maker, Inventor, Engineer"
meta_author: Kowin Shi

about:
  header: About
  content:
      left: By day, I solve robotics problems to reduce herbicide usage and improve yield for farmers.
      right: By night, I work on a diverse selection of projects, including custom 3D printers, racing sims, machine learning, financial analysis, and this website.
      bottom: I grew up in China and Canada, but have spent the last decade in the United States.
      bottom_disc: I currently reside in Bay Area CA.
  history:
    header: My Journey
    content:
      left:
        header: Education
        list:
          - item: Cornell University
          - item: B.S. in Mechanical Engineering, Minor in ECE
          - item: Master of Engineering in ECE
      center:
        header: Past
        list:
          - item: Amazon, Prime Air
          - item: Aurora Innovation, Compute Design Team
          - item: Uber ATG, Modules Team (Acquired by Aurora)
          - item: Tesla, Power Electronics Test Team
          - item: Tesla, Motor Design Team
          - item: GAC Automotive Engineering Institute
      right:
        header: Present
        list:
          - item: Blue River Technology (John Deere)
          - item: Mechatronics Engineer
  interests:
    header: Skills (Years of Experience)
    content:
      left:
        header: Hardware
        list:
          - item: Mechanical CAD/CAM (<script>document.write( new Date().getFullYear() - 2024  + 10);</script>)
          - item: Structural/CFD/Heat Transfer Simulation (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: Electrical CAD, PCBA Bringup (<script>document.write( new Date().getFullYear() - 2024  + 5);</script>)
          - item: Automotive Harness Design (<script>document.write( new Date().getFullYear() - 2024  + 2);</script>)
          - item: Mass Manufacturing/Injection Molding (<script>document.write( new Date().getFullYear() - 2024  + 5);</script>)
          - item: Machining and Welding (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: 3D Printing (<script>document.write( new Date().getFullYear() - 2024  + 10);</script>)
          - item: Electro-Mechanical Integration (<script>document.write( new Date().getFullYear() - 2024  + 10);</script>)
          - item: Battery Design (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: Electrical/ICE Vehicle Systems Design (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: Robotics Systems Design (<script>document.write( new Date().getFullYear() - 2024  + 10);</script>)
          - item: Testing and Validation (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: GD&T (<script>document.write( new Date().getFullYear() - 2024  + 6);</script>)
      center:
        header: Software
        list:
          - item: Python (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: C/C++ (<script>document.write( new Date().getFullYear() - 2024  + 7);</script>)
          - item: Verilog (<script>document.write( new Date().getFullYear() - 2024  + 2);</script>)
          - item: Linux (<script>document.write( new Date().getFullYear() - 2024  + 5);</script>)
          - item: Embedded Systems (3)
          - item: Java (1)
          - item: PLC Ladder Logic (2)
          - item: ROS (<script>document.write( new Date().getFullYear() - 2024  + 2);</script>)
          - item: HTML/CSS/Javascript (<script>document.write( new Date().getFullYear() - 2024  + 3);</script>)
          - item: Robotics Algorithms (<script>document.write( new Date().getFullYear() - 2024  + 4);</script>)
          - item: Optimal Control Algorithms (2)
          - item: Machine Learning Algorithms/Frameworks (2)
          - item: Hardware Acceleration, CUDA (1)
      right:
        header: Misc
        list:
          - item: Mandarin (Native Proficiency)
          - item: Spanish (Limited Working Proficiency)
          - item: Financial Analysis (3)
  tools:
    header: Tools I Use
    list:
      - logo: <img src="img/tools/catia.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/solidworks.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/nx.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/inventor.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/enovia.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/fusion.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/ansys.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/altium.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/eagle.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/autocadelectrical.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/simplify.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/python.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/cpp.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/ros.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/tf.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/pytorch.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/cuda.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/git.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/ubuntu.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/rpi.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/xilinx.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/intel_fpga.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/matlab.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/keil.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/atmelstudio.jpg" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/mplabx.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/arduino.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/rslogix.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/premiere_ps.png" class="img-responsive img-centered shadowed">
      - logo: <img src="img/tools/maya.png" class="img-responsive img-centered shadowed">
      
  button:
    text: Download My Resume
    href: /resume/Kowin_Shi_Resume.pdf

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname: https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: skookumasfrig

# If you have Google Analytics account setup, enter your tracker ID, eg. A-12312312-1
google_analytics_tracker_id: UA-175893800-1

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f6f6f6 #80B3FF
  primary-dark: 343434
  primary-rgb: "255,0,0" #"128,179,255"
  secondary-light: 58635a #FD6E8A
  secondary: 38433a #FD6E8A
  secondary-dark: 101010 #A2122F
  blog-text: 343434
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Portfolio settings
portfolio:
  labels:
    client: Client
    project-date: Date
    application: Application
    languages: Languages
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: San Francisco, CA
  copyright: Kowin Shi. All Rights Reserved.
  social: My Other Whereabouts
  new-thoughts: New Thoughts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    tooltip: "Github: Code I am writing"
    url: https://github.com/SkookumAsFrig
  - title: linkedin
    tooltip: "Linkedin: Places I've worked"
    url: http://www.linkedin.com/in/kowin-shi

plugins:
  - jekyll-compress-images
  - jekyll-resize

baseurl: ""

imageoptim:
  svgo: false
  verbose: false
  allow_lossy: true
  jpegoptim:
    allow_lossy: true
    max_quality: 50
  jpegrecompress:
    allow_lossy: true
    quality: 1

compress_images:
  images_path: "img/blog/**/*.{png,jpg,jpeg,svg,gif}"

exclude:
  - _compress_images_cache.yml


# Credits content
credits: '<a href="https://github.com/bill-c-martin/bill-c-martin.github.io">Website built on Freelancer Jekyll Theme</a>'

# Build settings
permalink: pretty
