# Site settings
title: Kowin Shi
email: kowinshi@hotmail.com
url: http://skookumasfrig.github.io
description: "Maker, Inventor, Engineer"
meta_author: Kowin Shi

about:
  header: About
  content:
      left: By day, I design, test and build some of the most powerful vehicle computing platforms in the world to enable autonomy.
      right: By night, I work on a diverse selection of projects, including custom 3D printers, robotics, machine learning, and financial analysis.
      bottom: I grew up in China and Canada, but have spent the last decade or so in the United States.
      bottom_disc: I currently reside in Pittsburgh PA.
  history:
    header: My Journey
    content:
      left:
        header: Education
        list:
          - item: Cornell University
          - item: B.S. in Mechanical Engineering, Minor in ECE
          - item: Master of Engineering in ECE
      center:
        header: Past
        list:
          - item: GAC Automotive Engineering Institute
          - item: Tesla, Motor Design Team
          - item: Tesla, Power Electronics Test Team
          - item: Uber ATG, Modules Team
      right:
        header: Present
        list:
          - item: Uber ATG
          - item: Autonomy Hardware Engineer
  interests:
    header: Skills (Years of Experience)
    content:
      left:
        header: Hardware
        list:
          - item: Mechanical CAD/CAM (8)
          - item: Structural/CFD/Heat Transfer Simulation (5)
          - item: Electrical CAD, PCBA Bringup (3)
          - item: Mass Manufacturing/Injection Molding (3)
          - item: Machining and Welding (5)
          - item: 3D Printing (8)
          - item: Electro-Mechanical Integration (8)
          - item: Electrical/Combustion Vehicle Systems Design (5)
          - item: Robotics Systems Design (8)
          - item: Design Evaluation and Methodology (5)
          - item: GD & T (4)
      center:
        header: Software
        list:
          - item: C/C++ (5)
          - item: Embedded Systems (4)
          - item: Python (5)
          - item: Verilog (2)
          - item: PLC Ladder Logic (2)
          - item: Java (2)
          - item: Linux (3)
          - item: ROS (2)
          - item: Robotics Algorithms (2)
          - item: Optimal Control Algorithms (3)
          - item: Machine Learning Algorithms/Frameworks (2)
          - item: Hardware Acceleration, CUDA (2)
      right:
        header: Misc
        list:
          - item: Mandarin (Native Proficiency, Bilingual Technical Communications)
          - item: Spanish (Limited Working Proficiency)
          - item: Financial Statement Analysis (1)
  button:
    text: Download My Resume
    href: /resume/kss223_resume.pdf

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname: https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# If you have Google Analytics account setup, enter your tracker ID, eg. A-12312312-1
google_analytics_tracker_id:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 101010 #80B3FF
  primary-rgb: "255,0,0" #"128,179,255"
  secondary-light: 58635a #FD6E8A
  secondary: 38433a #FD6E8A
  secondary-dark: 18231a #A2122F
  blog-text: 222
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Portfolio settings
portfolio:
  labels:
    client: Client
    project-date: Date
    application: Application
    languages: Languages
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: Pittsburgh, PA
  copyright: Kowin Shi. All Rights Reserved.
  social: My Other Whereabouts
  new-thoughts: New Thoughts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    tooltip: "Github: Code I am writing"
    url: https://github.com/SkookumAsFrig
  - title: linkedin
    tooltip: "Linkedin: Places I've worked"
    url: http://www.linkedin.com/in/kowin-shi

# Credits content
credits: '<a href="https://github.com/bill-c-martin/bill-c-martin.github.io">Website built from Jekyll Template</a>'

# Build settings
permalink: pretty
